'use client';

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import { PageHeader } from '@/components/layout/page-header';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select } from '@/components/ui/select';
import { FormField, FormLabel, FormMessage } from '@/components/ui/form';
import { SURGEON_OPTIONS, GLEASON_OPTIONS, GRADE_GROUP_MAP, CLINICAL_STAGE_OPTIONS } from '@/config/clinical-options';
import { SurgeonCode } from '@/types/common';
import { GleasonGrade, ClinicalStage } from '@/types/cancer';
import { PatientFullRecord } from '@/types/patient';
import { generateFollowUpSchedule } from '@/features/follow-ups/dates';
import { calculateAge } from '@/lib/date';
import { db } from '@/lib/api-client';
import { UserPlus, Save, ArrowLeft } from 'lucide-react';
import Link from 'next/link';

export default function NewPatientPage() {
  const router = useRouter();

  const [firstName, setFirstName] = useState('');
  const [surname, setSurname] = useState('');
  const [dateOfBirth, setDateOfBirth] = useState('');
  const [nhsNumber, setNhsNumber] = useState('');
  const [hospitalNumber, setHospitalNumber] = useState('');
  const [primarySurgeon, setPrimarySurgeon] = useState<SurgeonCode>('VK');

  // Baseline data optional step
  const [psa, setPsa] = useState('');
  const [gleasonGrade, setGleasonGrade] = useState<GleasonGrade>('3+4');
  const [clinicalStage, setClinicalStage] = useState<ClinicalStage>('2A');
  const [percentPositiveWorst, setPercentPositiveWorst] = useState('50');
  const [percentPositiveBest, setPercentPositiveBest] = useState('20');
  const [ukbScore, setUkbScore] = useState('40');

  const [error, setError] = useState('');
  const [isSaving, setIsSaving] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!firstName || !surname || !dateOfBirth || !nhsNumber || !hospitalNumber) {
      setError('Please fill in all mandatory demographic fields.');
      return;
    }
    setError('');
    setIsSaving(true);

    try {
      const patient = await db.createPatient({
        firstName,
        surname,
        dateOfBirth,
        nhsNumber,
        hospitalNumber,
        primarySurgeon,
      });

      // Baseline is optional at registration; saved as its own row when given.
      if (psa) {
        await db.updateBaseline(patient.id, {
          psa: parseFloat(psa) || 0,
          psaDate: new Date().toISOString().split('T')[0],
          gleasonGrade,
          percentPositiveCoresWorst: parseInt(percentPositiveWorst, 10) || undefined,
          percentPositiveCoresBest: parseInt(percentPositiveBest, 10) || undefined,
          ukbScore: parseInt(ukbScore, 10) || undefined,
          clinicalStage,
        });
      }

      // The follow-up schedule is generated by the database once an operation
      // date is recorded — not at registration.
      router.push(`/patients/${patient.id}`);
    } catch (err) {
      setIsSaving(false);
      setError(err instanceof Error ? err.message : 'Could not register patient.');
    }
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <PageHeader
        title="Register New RALP Patient"
        description="Onboard a new patient to the surgical outcomes database with baseline oncological profile"
        breadcrumbs={[
          { label: 'Patients', href: '/patients' },
          { label: 'Register New Patient' },
        ]}
      />

      <form onSubmit={handleSubmit} className="space-y-6">
        {/* Section 1: Demographics */}
        <Card className="shadow-sm">
          <CardHeader className="p-5 pb-3 border-b">
            <CardTitle className="text-sm font-bold text-foreground dark:text-slate-100 flex items-center gap-2">
              <UserPlus className="h-4 w-4 text-primary" />
              <span>1. Mandatory Patient Demographics</span>
            </CardTitle>
          </CardHeader>
          <CardContent className="p-5 space-y-4">
            {error && <div className="p-3 bg-destructive/10 border border-destructive/20 text-destructive text-xs rounded-lg">{error}</div>}

            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
              <FormField>
                <FormLabel>First Name *</FormLabel>
                <Input
                  value={firstName}
                  onChange={(e) => setFirstName(e.target.value)}
                  placeholder="e.g. Arthur"
                  required
                />
              </FormField>

              <FormField>
                <FormLabel>Surname *</FormLabel>
                <Input
                  value={surname}
                  onChange={(e) => setSurname(e.target.value)}
                  placeholder="e.g. Pendleton"
                  required
                />
              </FormField>

              <FormField>
                <FormLabel>Date of Birth *</FormLabel>
                <Input
                  type="date"
                  value={dateOfBirth}
                  onChange={(e) => setDateOfBirth(e.target.value)}
                  required
                />
              </FormField>

              <FormField>
                <FormLabel>NHS Number (10 digits) *</FormLabel>
                <Input
                  value={nhsNumber}
                  onChange={(e) => setNhsNumber(e.target.value)}
                  placeholder="e.g. 482 910 3341"
                  required
                />
              </FormField>

              <FormField>
                <FormLabel>Hospital Number (MRN) *</FormLabel>
                <Input
                  value={hospitalNumber}
                  onChange={(e) => setHospitalNumber(e.target.value)}
                  placeholder="e.g. RALP-78205"
                  required
                />
              </FormField>

              <FormField>
                <FormLabel>Primary Consultant Surgeon *</FormLabel>
                <Select
                  value={primarySurgeon}
                  onChange={(e) => setPrimarySurgeon(e.target.value as SurgeonCode)}
                >
                  {SURGEON_OPTIONS.map((s) => (
                    <option key={s.value} value={s.value}>
                      {s.fullName} ({s.value})
                    </option>
                  ))}
                </Select>
              </FormField>
            </div>
          </CardContent>
        </Card>

        {/* Section 2: Baseline Cancer Profile */}
        <Card className="shadow-sm">
          <CardHeader className="p-5 pb-3 border-b">
            <CardTitle className="text-sm font-bold text-foreground dark:text-slate-100">
              2. Pre-Operative Cancer Baseline (Optional / Initial Diagnostic)
            </CardTitle>
          </CardHeader>
          <CardContent className="p-5 space-y-4">
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
              <FormField>
                <FormLabel>Pre-Op PSA (ng/mL)</FormLabel>
                <Input
                  type="number"
                  step="0.01"
                  value={psa}
                  onChange={(e) => setPsa(e.target.value)}
                  placeholder="e.g. 8.4"
                />
              </FormField>

              <FormField>
                <FormLabel>Biopsy Gleason Grade</FormLabel>
                <Select
                  value={gleasonGrade}
                  onChange={(e) => setGleasonGrade(e.target.value as GleasonGrade)}
                >
                  {GLEASON_OPTIONS.map((g) => (
                    <option key={g} value={g}>
                      {g} (Grade Group {GRADE_GROUP_MAP[g]})
                    </option>
                  ))}
                </Select>
              </FormField>

              <FormField>
                <FormLabel>Clinical Stage</FormLabel>
                <Select
                  value={clinicalStage}
                  onChange={(e) => setClinicalStage(e.target.value as ClinicalStage)}
                >
                  {CLINICAL_STAGE_OPTIONS.map((st) => (
                    <option key={st.value} value={st.value}>
                      {st.label}
                    </option>
                  ))}
                </Select>
              </FormField>

              <FormField>
                <FormLabel>% Positive Cores (Worst)</FormLabel>
                <Input
                  type="number"
                  value={percentPositiveWorst}
                  onChange={(e) => setPercentPositiveWorst(e.target.value)}
                  placeholder="e.g. 50"
                />
              </FormField>

              <FormField>
                <FormLabel>% Positive Cores (Best)</FormLabel>
                <Input
                  type="number"
                  value={percentPositiveBest}
                  onChange={(e) => setPercentPositiveBest(e.target.value)}
                  placeholder="e.g. 20"
                />
              </FormField>

              <FormField>
                <FormLabel>UKB Score (1-100)</FormLabel>
                <Input
                  type="number"
                  value={ukbScore}
                  onChange={(e) => setUkbScore(e.target.value)}
                  placeholder="e.g. 40"
                />
              </FormField>
            </div>
          </CardContent>
        </Card>

        {/* Action Buttons */}
        <div className="flex items-center justify-between pt-4">
          <Link href="/patients">
            <Button variant="ghost" type="button" className="gap-1.5">
              <ArrowLeft className="h-4 w-4" /> Cancel
            </Button>
          </Link>
          <Button type="submit" className="gap-2 shadow-sm">
            <Save className="h-4 w-4" />
            <span>Create Patient & Initialize Schedule</span>
          </Button>
        </div>
      </form>
    </div>
  );
}
